### ISSUE TITLE
get all registered States and Intents

### ISSUE THREAD

**Issue by dp-thomas** [webcomputing/AssistantJS#24]
Hi,

I was wondering if there's an easy way to retrieve a list of all `states`  and its `intents`?`

Thanks for your help!

**Comment by Novaal** [comment]
Hi @dp-thomas,

thanks for your question. Unfortunately this is not possible at the moment. But this would be very useful for the cli. Feel free to open a Pull-Request! :-)

Best regards

**Comment by antoniusostermann** [comment]
Hey @dp-thomas,

what you can do is inject the `MetaState` information via `core:state-machine:meta-states` (https://github.com/webcomputing/AssistantJS/blob/master/src/components/state-machine/descriptor.ts#L45). This gives you an array of state names with registered intent methods per state (see: https://github.com/webcomputing/AssistantJS/blob/develop/src/components/state-machine/public-interfaces.ts#L86). :-) 

Greetings

Toni

**Comment by dp-thomas** [comment]
Thanks @antoniusostermann ! That's exactly what I needed
