### ISSUE TITLE
Tutorial for v0.2.7 - TypeError: Cannot read property 'hget' of undefined

### ISSUE THREAD

**Issue by jvondrus** [webcomputing/AssistantJS#63]
Hello,
first I want to say big thanks for perfect video tutorial to going pass through the program.

I'm running on RasPi (Linux raspberrypi 4.19.34-v7+) with node v11.14.0, but I can't make it works :(

I did every step as video says, just skip alexa (I will use just google), tsc is without error, build for 'apiai' too, server also running, but when I try post some question via 'apiai', I'm getting error about 'hget' function. But 'hget' is part of 'redis' and it's also installed with version v.2.8.0 at 'node_modules'.

Do you know where can be my problem? Thank you very much.

Here is part of log:
[log.txt](https://github.com/webcomputing/AssistantJS/files/3104400/log.txt)

**Comment by ThWoywod** [comment]
Hello @jvondrus,
thank you for using AssistantJS and give it a try. It looks like your redis instance will be `undefined`. So I thinks your miss to configure the Redis Client. (https://github.com/webcomputing/AssistantJS/wiki/Redis-integration)

Are you able to share your current code? Then I will take a look.

**Comment by jvondrus** [comment]
Hello,
you are right, I missed the Redis configuration. Your tutorial video is without redis (at component.ts), so I did it same.
I don't have any specific code yet, this is my first step with AssistantJS (and also with TypeScript), I'm making my test "Bus app".

[components.ts.txt](https://github.com/webcomputing/AssistantJS/files/3111370/components.ts.txt)
[index.ts.txt](https://github.com/webcomputing/AssistantJS/files/3111371/index.ts.txt)

**Comment by ThWoywod** [comment]
Hi @jvondrus,

in your `components.ts` file you have to configure the redis instance by defining the `servicesConfiguration` like below.

```
import * as fakeRedis from "fakeredis";
...
const servicesConfiguration: servicesInterfaces.Configuration = {
  redisClient: fakeRedis.createClient({ fast: true })
};
...
export default {
  "core:i18n": i18nConfiguration,
  "core:services": servicesConfiguration,
  "core:unifier": unifierConfiguration,
  "apiai": apiAiConfiguration
}
```
If you prefer to use a real redis instance instead of using a fake redis you will be able to configure the `servicesConfiguration` like this.

```
import { RedisClient } from "redis";
...
const servicesConfiguration: servicesInterfaces.Configuration = {
  redisClient: new RedisClient({
    db: "...",
    host: "...",
    password: "...",
    port: "..."
  })
};
...
export default {
  "core:i18n": i18nConfiguration,
  "core:services": servicesConfiguration,
  "core:unifier": unifierConfiguration,
  "apiai": apiAiConfiguration
}
```

**Comment by jvondrus** [comment]
Hi, thank you very much.
